org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft version
minecraft_version=26.1.1
# Fabric Loader version
loader_version=0.18.4
# Fabric API version
fabric_version=0.145.4+26.1.1
# Yarn Mappings version
yarn_mappings=1.21.7+build.8

mod_id=time_machine
mod_name=time machine fabric
mod_license=All Rights Reserved
mod_version=26.1.1
mod_group_id=com.time_machine
mod_authors=varun
mod_description=hi
